// Made by `npm run upgrades` from data/upgrades.csv. Edit the CSV, not this file.
import type { UpgradeRow } from './csv'

export const UPGRADE_ROWS: readonly UpgradeRow[] = [
  {"object":"cooker","tier":1,"name":"Basic oven","price":0},
  {"object":"cooker","tier":2,"name":"Two-oven range","price":25},
  {"object":"cooker","tier":3,"name":"Fancy professional kitchen","price":50},
  {"object":"fridge","tier":1,"name":"Small under-counter fridge","price":0},
  {"object":"fridge","tier":2,"name":"Fridge-freezer","price":20},
  {"object":"fridge","tier":3,"name":"American-style fridge","price":40},
  {"object":"door","tier":1,"name":"Old wooden door","price":0},
  {"object":"door","tier":2,"name":"Door with knocker and peephole","price":15},
  {"object":"door","tier":3,"name":"Smart door with doorbell camera","price":35},
  {"object":"broom","tier":1,"name":"Broom","price":0},
  {"object":"broom","tier":2,"name":"Hoover","price":20},
  {"object":"broom","tier":3,"name":"Robot hoover","price":45},
  {"object":"petbowl","tier":1,"name":"Plain pet bowl","price":0},
  {"object":"petbowl","tier":2,"name":"Bowl with the pet's name on it","price":10},
  {"object":"petbowl","tier":3,"name":"Automatic feeder","price":30},
  {"object":"tv","tier":1,"name":"Old box telly","price":0},
  {"object":"tv","tier":2,"name":"Big flat-screen TV","price":25},
  {"object":"tv","tier":3,"name":"Cinema wall with surround sound","price":50},
  {"object":"bookshelf","tier":1,"name":"Wobbly shelf","price":0},
  {"object":"bookshelf","tier":2,"name":"Proper bookcase","price":20},
  {"object":"bookshelf","tier":3,"name":"Library wall with a ladder","price":40},
  {"object":"piano","tier":1,"name":"Old upright piano","price":0},
  {"object":"piano","tier":2,"name":"Shiny upright piano","price":25},
  {"object":"piano","tier":3,"name":"Grand piano","price":50},
  {"object":"bed","tier":1,"name":"Creaky single bed","price":0},
  {"object":"bed","tier":2,"name":"Comfy double bed","price":30},
  {"object":"bed","tier":3,"name":"Royal four-poster","price":55},
  {"object":"phone","tier":1,"name":"Old dial phone","price":0},
  {"object":"phone","tier":2,"name":"Cordless phone","price":20},
  {"object":"phone","tier":3,"name":"Video phone","price":40},
  {"object":"desk","tier":1,"name":"Little desk","price":0},
  {"object":"desk","tier":2,"name":"Writing bureau","price":20},
  {"object":"desk","tier":3,"name":"Inventor's desk","price":40},
  {"object":"basin","tier":1,"name":"Chipped wash basin","price":0},
  {"object":"basin","tier":2,"name":"Basin with a shower","price":20},
  {"object":"basin","tier":3,"name":"Spa bathroom with rainfall shower","price":45},
  {"object":"toilet","tier":1,"name":"Clanky loo","price":0},
  {"object":"toilet","tier":2,"name":"Quiet-flush loo","price":15},
  {"object":"toilet","tier":3,"name":"Heated-seat loo with music","price":35},
  {"object":"telescope","tier":1,"name":"Brass telescope","price":0},
  {"object":"telescope","tier":2,"name":"Big spyglass on a stand","price":20},
  {"object":"telescope","tier":3,"name":"Observatory telescope","price":45},
  {"object":"lamp","tier":1,"name":"Oil lamp","price":0},
  {"object":"lamp","tier":2,"name":"Electric lamp","price":30},
  {"object":"lamp","tier":3,"name":"Mega beam","price":55},
  {"object":"garden","tier":1,"name":"Veg patch","price":0},
  {"object":"garden","tier":2,"name":"Raised beds","price":20},
  {"object":"garden","tier":3,"name":"Greenhouse","price":45},
  {"object":"jetty","tier":1,"name":"Rickety jetty","price":0},
  {"object":"jetty","tier":2,"name":"Proper jetty","price":25},
  {"object":"jetty","tier":3,"name":"Harbour with boat shed","price":50},
  {"object":"boat","tier":1,"name":"Rowing boat","price":0},
  {"object":"boat","tier":2,"name":"Tug","price":30},
  {"object":"boat","tier":3,"name":"Speedboat","price":60},
  {"object":"tank","tier":1,"name":"Small fish tank","price":0},
  {"object":"tank","tier":2,"name":"Big tank","price":25},
  {"object":"tank","tier":3,"name":"Wall-sized reef tank","price":50},
  {"object":"barometer","tier":1,"name":"Barometer","price":0},
  {"object":"barometer","tier":2,"name":"Weather instruments","price":20},
  {"object":"barometer","tier":3,"name":"Weather computer","price":45},
  {"object":"radio","tier":1,"name":"Crackly radio","price":0},
  {"object":"radio","tier":2,"name":"Ship-to-shore radio","price":20},
  {"object":"radio","tier":3,"name":"Coastguard radio desk","price":45},
  {"object":"console","tier":1,"name":"Old computer","price":0},
  {"object":"console","tier":2,"name":"Gaming PC","price":25},
  {"object":"console","tier":3,"name":"Supercomputer wall","price":55},
  {"object":"gadgets","tier":1,"name":"Workbench","price":0},
  {"object":"gadgets","tier":2,"name":"Gadget bench","price":25},
  {"object":"gadgets","tier":3,"name":"Robot lab","price":55},
]
