"""Authored review data. All new numeric balancing is a proposal, never runtime wiring."""
import json
from pathlib import Path
HERE=Path(__file__).parent
# id | name | category | dependencies | activities | varied unlock challenge | layout | items (id:profile) | props | decision
DATA='''
kitchen|Kitchen / entrance|standard|none|Cook; snack; tidy; greet; feed cat|Day-one essential, never quiz-gated|Door left; fridge and range centre; tools and bowl right|door:door,fridge:storage,cooker:cook,broom:clean,petbowl:pet|worktop,wall_shelf,hooks|locked
living|Living room|standard|none|TV; reading; music; sofa nap|Day-one relaxation|TV left; shelf centre; piano right; sofa foreground|tv:fun,bookshelf:research,piano:music|sofa,rug,sea_chart|locked
bedroom|Bedroom with en suite|standard|none|Sleep; call; diary; wash; loo|Day-one essentials|Bed left; phone and desk centre; partition at x74; bathroom right|bed:sleep,phone:social,desk:research,basin:wash,toilet:loo|bedside_table,mirror,privacy_door|locked
lamp|Lamp room / inset lantern cap|lantern_cap|none|Light and polish lamp; spot ships|Day-one ship-safety duty|Inset glazed iron lantern chamber; lamp centre; wraparound external walkway and telescope; no full-width domestic room|telescope:spot,lamp:light|lantern_glass,wrap_rail|locked
workshop|Workshop|standard|breakdowns|Repair; choose parts; build inventions|Repair distinct fault types; choose tools; assemble a working mechanism|Parts drawers left; workbench centre; test jig right|repairbench:repair,partsbin:storage,testjig:craft|pegboard,tool_rack|review: global fault reduction needs playtesting
weather|Weather station|standard|none|Forecast; record rain and wind; warn ships|Observe weather at distinct times; interpret chart; issue correct warning|Gauge left; chart centre; radio right; external sensor feed|barometer:forecast,radio:signal,raingauge:measure,windvane:measure|forecast_chart,sensor_cable|locked geometry; future forecast simulation proposal
marine_lab|Marine laboratory|standard|aquarium; specimens from fishing or diving|Microscopy; habitat research; water testing|Match specimens to habitats; examine sample; balance water|Sample shelves left; microscope centre; test sink right|microscope:research,sampletank:capacity,waterkit:measure|specimen_jars,habitat_chart|review: separate lab or aquarium specialization
radio_room|Radio room|standard|power; aerial|Decode; rescue calls; relay locations|Repair aerial; decode short signal; relay chart location|Radio desk centre; signal board left; map right|radio:signal,signaldecoder:signal,aerial:signal|code_chart,headphones|review: standalone or weather-room expansion
map_room|Map and chart room|standard|sightings; boat for routes|Plot routes; discover islands; chart rocks|Orient recovered fragments; plot one safe route|Chart table centre; map archive left; route pins right|charttable:route,maparchive:research|compass_prop,map_fragments|approved idea
observatory|Observatory|standard|night sky; power optional|Stars; moon phases; direction puzzles|Identify constellations; use North Star to find a bearing|Scope left; star chart centre; moon dial right|telescope:spot,stardial:measure|star_chart,moon_phase_tiles|approved idea; no fixed height
library|Library|standard|bookshelf migration|Stories; lighthouse history; practical research|Recover and sort books; solve a repair using a passage|Migrated shelf left; reading desk centre; clue cabinet right|bookshelf:research,readingdesk:research|reading_chair,book_props|approved idea
music|Music room|standard|piano migration|Melodies; rhythm; visitor concert|Copy melody; identify sounds; perform for visitor|Piano left; percussion centre; accordion and record player right|piano:music,drums:music,accordion:music,gramophone:music|music_stand,score_props|approved idea
artist|Artist studio|standard|world colour discoveries|Paint; mix colours; pottery; decorate rooms|Mix two colours; make visitor picture; fire clay safely|Easel left; mixing table centre; pottery wheel right|easel:craft,potterywheel:craft,kiln:craft|paint_palette,clay_props,picture_frames|approved idea; kiln powered
computer|Curated computer room|standard|power; desk migration|Fictional mail; newspaper; forecasts; research; games|Order a reply; interpret a headline; research a practical task|Computer and migrated desk centre; message slots left; printer right|computer:research,desk:research,printer:craft|mail_cards,newspaper_tiles|locked curated content; no live internet
storage|Storage / box room (attic fantasy)|standard|none|Inspect clutter; search; move and stack boxes|Memorize a box field; recover requested part; stack safely|Three clear shelving zones; movable boxes foreground|boxrack:storage,searchchest:search|box_variants,lost_parts|approved idea; never forced above bedroom
food_store|Food store / larder|standard|kitchen; supplies|Store ingredients; plan meals; preserve surplus|Sort food by storage need; prepare varied meal basket|Dry shelves left; cool cabinet centre; basket station right|lardershelf:storage,preserver:storage|food_jars,ingredient_crates|discussed system link; room form review
 dining|Dining room|standard|kitchen; visitors; table migration|Meals; table setting; celebrations|Set correct places; serve varied meal; welcome visitor|Table centre; serving hatch left; dishes right|diningtable:social,servinghatch:cook|chairs,cutlery,celebration_bunting|approved idea
bank|Bank / savings room|standard|allowance; persistent savings|Count coins; deposit; withdraw; plan upgrade|Keep some allowance across days; verify counted receipt|Counter left; tube centre; safe right; readable account display|deposittube:bank,safe:storage,coinscales:measure|savings_book,receipt_props|review: capped interest amount and interval; balances never break
cinema|Cinema|standard|power; visitors|Fictional films; scene sequencing; adventure replays|Restore projector; order scenes; host screening|Screen left; benches centre; projector right|projector:fun,filmarchive:research|screen,benches,film_reels|approved idea
 games|Games hall|standard|games cabinet migration|Snooker; table tennis; darts; table football; board games|Complete aiming, timing and arithmetic rounds|One folding central table; replaceable game surface; wall darts|snooker:game,tabletennis:game,darts:game,tablefootball:game,boardgames:game|cues,balls,paddles,scoreboard|review: rotate game stations; cannot display all at once
playroom|Playroom|standard|none|Ball-pit search; soft play; trampoline timing|Find clue ball; traverse short course; time bounce|Pit left; soft obstacles centre; trampoline right|ballpit:search,softplay:game,trampoline:game|colour_balls,padded_blocks|approved idea
imagination|Imagination / themed room|standard|curated theme unlocks|Six scene puzzles on a reusable stage|Discover theme clue; complete its bespoke puzzle|One 105x35 interchangeable set; clear movement lane; control pedestal|themecontrol:game|scene_slots|review: theme selection and reward rules
zero_gravity|Zero-gravity room|standard|observatory; stored power|Float rings; orbit puzzle; recover floating items; astronaut training|Solve orbit sequence; reserve battery power; pass short floating course|Sealed entrance left; rings centre; padded nets and controls right|gravitycontrol:power,orbitboard:game|rings,padded_nets,floating_lunch|review: power unit and costume silhouette
conservatory|Conservatory|standard|decorative plants; visitors|Tea; read; social visits; tame overgrowth|Identify plant needs; arrange reading nook; host tea|Plants left; tea bench centre; reading seat right|teaset:social,plantstand:growing|decorative_plants,reading_seat|approved idea; indoor leisure not food greenhouse
pub|Family-friendly pub / inn|standard|visitors; kitchen|Lemonade; cocoa; meals; quizzes; dominoes; darts; stories|Prepare drink; solve team quiz; host storytelling|Counter left; tables centre; games right; rear guest WC|drinkcounter:social,dominoes:game,darts:game|bar_stools,story_cards|review: name; soft drinks only
pool|Swimming-pool floor|standard|boiler; pump; changing annex|Lengths; float; splash; retrieve; gentle rescue|Check water; use ladder; retrieve float; demonstrate rescue|Water ~90 percent; narrow foreground tile edge; ladder right; bathroom annex|poolpump:water,poolheater:heat|water_surface,inflatables,ladder|approved idea; bathroom annex preserves large water area
 gym|Gym|standard|exercise equipment migration|Exercise; balance; comic flex and headstand|Sequence warm-up; balance course; short varied workout|Exercise station left; mat centre; showers in annex right|exercisebike:fitness,weights:fitness|exercise_mat,balance_beam|discussed; detailed equipment proposal
boiler|Boiler room|standard|fuel or power; water services|Heat; pressure diagnosis; reset and test tap|Read pressure; select pipe/fuse/reset; test hot tap|Boiler centre; pipes left; gauge and service panel right|boiler:heat,pressuregauge:measure|pipe_set,radiator|approved idea; failure degrades water, never disables toilets
lair|Hidden underground lair|underground|Strange Rumblings mission|Gadgets; games; secret discoveries|Current mission counts digging, visitors and quiz clues; future bespoke mechanism puzzle proposed|Console left; gadget bench right; concealed rock walls|console:research,gadgets:craft|rock_lining,secret_door|runtime hook; terrain reveal only on unlock
ensuite|Bedroom en suite|subroom|bedroom|Wash; brush teeth; loo|Essential from day one|Within bedroom x74..110; opaque privacy door; basin then loo|basin:wash,toilet:loo|mirror,privacy_door|locked; no independent stack slot
pool_changing|Pool changing / bathrooms|service_bay|pool|Hidden outfit swap; shower; wash; loo|Included with pool; basic needs never gated|66x35 rear annex; cubicle left; basin and loo right|shower:wash,basin:wash,toilet:loo|changing_cubicle,privacy_door|proposal footprint; swimming suit reused
 gym_changing|Gym changing / shower|service_bay|gym|Wash; loo; dress|Included with gym|66x35 rear annex; shower left; fixtures right|shower:wash,basin:wash,toilet:loo|lockers,privacy_door|proposal footprint
pub_wc|Guest toilet|service_bay|pub|Wash; loo|Included with inn|44x35 rear service bay; privacy screens|basin:wash,toilet:loo|privacy_door,mirror|proposal footprint
service_wc|Distributed service WC|service_bay|walking-distance policy|Wash; loo|Add where saved layout exceeds three-band access target|44x35 rear bay; repeated fixture kit|basin:wash,toilet:loo|privacy_door,pipe_set|review: placement hook; never all fixtures broken at once
bath|Bath / laundry service possibility|service_bay|boiler; water; possible future laundry|Bath; wash clothes|Diagnose water; sort garments; test service|Proposed 55x35 utility bay; tub left; washer right|bathtub:wash,washer:clean|laundry_basket,pipe_set|discussed optional systems; do not produce until chosen
lift|Lift service core|service_core|current Puffed Out requires five above-ground floors|Fast travel; repair doors|Current mission; future safe load and door test|22x35 repeatable landing bay; vertical shaft extends with saved stack|lift:travel|landing_door,shaft_segment,indicator|review: rear versus side core; do not create final shaft art
stairs|Ladders / spiral stair core|service_core|none|Travel upward and downward|Basic ladder available; stair upgrade route exercise proposed|10x35 repeatable rear access lane|stairs:travel|ladder_segment,stair_segment|runtime stairs exist; transport tiers proposed
slide|Helter-skelter transport|service_core|tower height; dynamic exits|Fast downward travel; clear jam|Plot exit route; test flap; retrieve laundry|14x35 tube segment beside core; one exit each saved floor|slide:travel|tube_segment,flap,face_window|review: core clearance and exact wrapping; no final art
 dive|Bedroom dive / two-door changing bay|extension|bedroom; safe sea; outfit|Hidden change; board dive; sea splash|Test doors; demonstrate swimming; choose safe weather|Bedroom-local seam x117; hidden x118..130; exit x135; board beyond|diveboard:game,diveinner:single,diveouter:single|hidden_cubicle,board_support|locked attachment; playable hook absent; final length review
bbq|Kitchen BBQ balcony|extension|kitchen; ingredients; safe weather|Grill; picnic; feed visitor|Find dry weather; safe ignition; cook varied meal|55x35 kitchen-attached bay; grill left; prep shelf right|bbq:cook,awning:weatherproof|prep_shelf,visitor_stool|approved idea; strong wind/lightning blocks regardless tier
hot_tub|Gym hot-tub cantilever|extension|gym; boiler; pump|Soak; socialize; winter comfort|Test heat and pump; select safe temperature|55x35 gym-attached platform; tub centre; rail and access left|hottub:heat,tubpump:water|rail,water_surface|approved idea; structure needs review
caged_trampoline|Exterior caged trampoline|extension|playroom; safe weather|Timing; comic high bounce|Test cage; land three timed bounces|55x35 playroom bay; spring bed centre; tall safety cage|trampoline:game|safety_cage,spring_support|review: maximum bounce and roof camera hook
bowling|Bowling alley telescopic bay|extension|long horizontal island expansion|Aim; timing; scoring|Align lane; roll controlled bowl; count score|165x35 bay; release left; pins right|bowlinglane:game,pinsetter:craft|bowling_ball,pins,lane_markings|review: parent attachment and expansion clearance
kitchen_bay|Expanded kitchen bay|extension|kitchen; cooking progression|Batch meals; visitor cooking|Prepare multi-course meal; allocate burners|55x35 kitchen bay; extra work surfaces and utility seam|cooker:cook,fridge:storage|worktop,serving_hatch|discussed architecture; not replacement for fixed core
 gaming_bay|Gaming extension|extension|computer or living parent|Curated games; cooperative puzzles|Solve cooperative puzzle and choose station|55x35 parent bay; console left; seat right|console:research|game_seat,screen|review: parent and distinction from lair/games hall
roof|Lamp-room roof / parachute launch|extension|maximum tower; wind safety|Late comic parachute descent|Demonstrate safe landing; select calm forecast|110x20 roof; launch hatch; clear lamp beam|parachutepack:single|roof_hatch,landing_marker|possible late idea; maximum height and safety decision unresolved
 garden|Garden / raised beds|island|mission unlock; seed supplies|Grow; harvest; water; dig|Choose sunny site; match seeds; nurture and harvest mixed crop|55x25 patch; three crop slots; fence edge|garden:growing,wateringcan:single|soil_tile,crop_stages,fence|mission design proposed; absent day one in final design
 greenhouse|Food greenhouse|island|garden; irrigation|Protected crops; water; repair glass|Balance water; grow varied crop; replace glass panel|66x35 glass house; beds left; irrigation right|garden:growing,irrigation:water|glass_panels,crop_stages|proposed separate place or garden tier 3 same asset
orchard|Orchard|island|island expansion; planting|Fruit; pruning; harvest|Identify saplings; plan spacing; harvest seasonal fruit|88x40 terrace; trees in three zones; clear walkway|fruittree:growing|tree_stages,fruit_crate|approved expansion idea; season simulation review
jetty|Jetty / harbour|island|mission unlock; shoreline|Fish; launch; load supplies|Tie knots; select safe tide; catch and identify fish|55x15 dock; floor plane stable; water below|jetty:fish|bollard,rope,buoy|owned repairable; fishing remains reachable
boathouse|Boathouse / indoor dry dock|island|shoreline expansion; boat; weather|Launch; fuel; clean; repair; load; berth upgrades|Open inlet; check hull; load supplies; safe practice trip|110x50 shore facility; water berth centre; repair bench left; fuel and doors right|boat:boat,seadoors:capacity,fuelpump:capacity,marinebench:repair,berth:capacity|indoor_water,buoy,seaweed,cargo|approved replacement for garage; capacity/fuel tuning proposal
shop|Off-island shop|destination|boat; safe route|Buy supplies; reserve orders; meet proprietor|Early route puzzle and first shopping trip|66x35 destination; shopfront left; landing right|shop:single|shop_counter,supplies,proprietor|not keeper-owned; no broken or repair state
coop|Chicken coop|island|mission unlock; food|Feed; eggs; tidy; latch repair|Build latch; identify feed; care routine with distinct tasks|55x35 patch; coop left; run right|coop:pet,eggtray:storage|chicken_idle,chicken_peck,straw|approved idea; no day-one coop
lido|Outdoor pool / lido|island|boiler; water pump; expanded terrace|Swim; float; picnic; gentle rescue|Check water; rescue float; warm pool|110x45 terrace; large water basin and tiled edge|poolpump:water,poolheater:heat|water_surface,ladder,changing_cubicle|approved spectacle idea; footprint proposal
rescue|Rescue station / helipad|island|radio; weather; rescue gear|Prepare equipment; signal; rescue dispatch|Relay location; choose gear; secure terrace|110x40 cliff terrace; pad centre; equipment left|rescuewinch:capacity,rescuecabinet:storage|helipad_marking,helicopter,firstaid_props|review: rescue vehicle and playable dispatch
wind|Wind turbine|island|power routing; wind forecast|Generate; brake; clear mechanical fault|Secure foundation; match windy site; route circuit|44x70 terrace; mast vertical; stable base|windturbine:power|foundation,wind_cable|approved expansion idea; power units proposed
funicular|Cliff funicular|island|cliff track to jetty; power|Ride; carry supplies; repair track|Align track; test brake; deliver crate|55x70 cliff route; two terminal stations|funicular:travel|track,terminal,carriage|review: island levels and route length
geothermal|Geothermal heating plant|underground|drill; heating pipe network|Heat; pressure control; steam repair|Find warm ground; control pressure; test hot tap|110x50 below new terrace; drill left; exchanger right|drill:craft,heatexchanger:heat|rock_layers,steam_vent,pipe_set|approved idea; below terrain not standard stack
sea_tunnel|Sea-life underwater tunnel|underground|shoreline expansion; seal integrity|Observe wildlife; identify habitats|Inspect seals; match species; trace safe exit|165x35 below shoreline; glass passage with clear walking lane|tunnelseals:weatherproof|glass_segments,sea_creatures,exit_sign|review: underwater stage and viewing mechanics
satellite|Satellite dish / radio mast|island|signal network; expanded terrace|Relay; align; signal puzzles|Decode direction; align dish; test message|66x50 terrace; dish centre; support legs and service box|dish:signal,mast:signal|support_legs,cable|approved expansion idea; no real internet
 testing_yard|Workshop testing yard|island|workshop; island expansion|Test inventions; labour-saving machines|Assemble safe mechanism; test fault; demonstrate useful output|110x35 terrace; marked test lane; tools left; barriers right|testtrack:craft,butler:clean|safety_barrier,crate_targets|approved expansion idea; invention scope review
solar|Solar terraces / folding wall array|island|power cut; forecasts; battery; circuit puzzle|Charge; prioritize lamp/boiler/lift; clear snow; repair glass|Find sunny site; repair circuit; route battery to lamp|Basic 22x12 rail panel; mid 44x24 folding array; top 110x35 island field|solarpanel:power,battery:power,powerrouter:power|panel_mount,cable,snow_overlay|review: tier 4 sun tracker considered optional, not silently removed
solar_tracker|Comic sun-tracking array|island|solar; tracking decision|Track sun; reset mistaken bright-target tracking|Compare sky targets; calibrate sensor|66x35 solar terrace add-on; tracking mount on stable base|suntracker:power|tracking_mount,brightness_targets|discussed fourth tier; separate optional module pending approval
castle_theme|Castle theme|theme|imagination room|Shield sequence; rescue toy|Match heraldry then solve drawbridge sequence|Same 105x35 set; gate left; toy castle centre|drawbridge:single|banners,castle_backdrop,shield_tiles|discussed variant; no stack slot
space_theme|Space-station theme|theme|imagination room|Orbit ordering; docking puzzle|Place planets then dock toy capsule|Same 105x35 set; star panel and docking port|toyairlock:single|space_backdrop,planet_tiles|discussed variant; distinct from permanent zero-gravity room
pirate_theme|Pirate-ship theme|theme|imagination room|Chart clues; knot sequence|Plot toy treasure route and tie knot|Same 105x35 set; helm left; chart right|toyhelm:single|pirate_backdrop,treasure_props|discussed variant
jungle_theme|Jungle theme|theme|imagination room|Animal clues; vine path|Match tracks then cross short path|Same 105x35 set; tracks left; vines right|vinegate:single|jungle_backdrop,animal_tracks|discussed variant
haunted_theme|Gentle haunted theme|theme|imagination room|Sound matching; hidden toy|Identify silly sound then find puppet|Same 105x35 set; puppet box centre|puppetbox:single|haunted_backdrop,comic_ghost|discussed variant; child-friendly
arctic_theme|Arctic-base theme|theme|imagination room|Warmth routing; ice rescue|Route pretend heat and rescue toy penguin|Same 105x35 set; pretend generator left; ice right|toyheater:single|arctic_backdrop,penguin_toy|discussed variant
 garage|Garage (superseded)|retired|none|Historical idea replaced by water-filled boathouse|No unlock; do not implement|No allocated geometry|none|none|retired: boathouse replaces garage
'''
PROFILES={
'fun':(['30 fun / 40 game min','38 fun / 34 game min','45 fun / 28 game min'],'watch_tv','screen static / 4-frame channel flicker / cracked screen'),
'research':(['1 clue per 20 game min','2 clues per 17 game min','3 clues per 14 game min'],'read','idle page / 4-frame page or display change / stuck page or screen'),
'music':(['30 fun and 4 social / 30 min','38 fun and 5 social / 26 min','45 fun and 6 social / 21 min'],'piano','idle / 4-frame keys or bellows / stuck key'),
'social':(['12 social / 20 min','15 social / 17 min','18 social / 14 min'],'phone','idle / 4-frame serving or ring / jam or dead signal'),
'storage':(['4 item slots','8 item slots','12 item slots'],'reach_use','closed / 4-frame opening / jammed hinge; contents never destroyed'),
'capacity':(['1 cargo or task slot','2 cargo or task slots','3 cargo or task slots'],'reach_use','idle / 4-frame transfer / jammed mechanism'),
'cook':(['1 recipe serving / 35 min','2 servings / 30 min','3 servings / 25 min'],'cook_back','cold / 4-frame flame or service motion / sputtering burner'),
'clean':(['40 tidiness / 25 min','50 tidiness / 21 min','60 tidiness / 18 min'],'tidy','parked / 4-frame tool motion / split bristle or stalled wheel'),
'pet':(['10 pet-care points / 12 min','15 pet-care points / 10 min','20 pet-care points / 8 min'],'chicken_care','still / 4-frame feeding / broken latch or feed jam'),
'sleep':(['80 percent morning energy','90 percent morning energy','100 percent morning energy'],'sleep','made / 4-frame blanket rise / exposed spring'),
'wash':(['40 hygiene / 15 min','50 hygiene / 13 min','60 hygiene / 11 min'],'wash_back','dry / 4-frame water / leaking tap'),
'loo':(['70 bladder / 8 min','88 bladder / 7 min','105 nominal bladder capped at 100 / 6 min'],'loo_hide','idle / 4-frame flush / cistern rattle'),
'spot':(['3 common spotting targets','6 targets with 1 extra zoom step','9 targets including whale and distant ship'],'telescope','still / 4-frame scan / jammed bearing'),
'light':(['4 game hours beam per fuel unit','8 game hours beam per fuel unit','full 14.5-hour game night/day cycle beam per charge'],'reach_use','off / 4-frame lit core / weak or stalled lens'),
'repair':(['25 game min per repair','20 game min per repair','15 game min per repair'],'cook_back','idle / 4-frame tool jig / jammed tool; repair still possible manually'),
'forecast':(['6 game hours warning','12 game hours warning','24 game hours warning'],'read','still dial / 4-frame needle / stuck dial'),
'signal':(['1 signal decoded / 20 min','2 signals / 17 min','3 signals / 14 min'],'phone','off / 4-frame signal lights / aerial crack or static'),
'measure':(['1 reliable reading or weighed batch / 10 min'],'reach_use','still / 4-frame reading / frozen dial'),
'craft':(['1 completed batch / 30 min','2 batches / 26 min','3 batches / 21 min'],'cook_back','idle / 4-frame tool movement / blocked spindle'),
'route':(['1 route with 3 waypoints','2 saved routes with 5 waypoints','3 saved routes with 7 waypoints'],'read','idle / 4-frame route highlight / stuck plotting arm'),
'search':(['1 searchable compartment / 15 min','2 compartments / 13 min','3 compartments / 11 min'],'reach_use','closed / 4-frame searching / stuck drawer'),
'game':(['10 fun per successful round / 12 min','13 fun / 10 min','15 fun / 8 min'],'reach_use','idle / 4-frame game motion / loose or jammed mechanism'),
'bank':(['1 deposit processed / 10 min','2 deposits / 8 min','3 deposits / 6 min'],'reach_use','still / 4-frame coin transfer / tube jam; saved balance untouched'),
'power':(['10 stored or generated energy units per clear game day','20 energy units per clear day','30 energy units per clear day'],'reach_use','off / 4-frame status lights / cracked cable or stalled motor'),
'growing':(['3 crop yields / 2 completed game days','6 crop yields / 2 days','9 crop yields / 2 days'],'dig','empty plus ripe1/2/3 / 4-frame watering / broken fence or glass'),
'water':(['clean 1 water bay / 20 min','2 bays / 17 min','3 bays / 14 min'],'wash_back','off / 4-frame water flow / leaking seal'),
'heat':(['heat 1 connected service bay per charge','heat 2 service bays per charge','heat 3 service bays per charge'],'reach_use','pilot / 4-frame pressure flame / gauge fault; cold fallback remains'),
'fitness':(['10 energy and 10 fun / 20 min','13 energy and 13 fun / 17 min','15 energy and 15 fun / 14 min'],'flex','idle / 4-frame cycling or lifting / stuck bearing'),
'travel':(['8 game min per floor or route segment','5 game min per segment','3 game min per segment'],'walk','closed / 4-frame travel/doors / jammed door; stairs remain usable'),
'weatherproof':(['usable in calm dry weather','also usable in light rain','also usable in moderate rain; never lightning/extreme wind'],'reach_use','idle / 4-frame deployment / torn seal'),
'fish':(['22 fun and 14 hunger / 45 min','28 fun and 18 hunger / 38 min','33 fun and 21 hunger / 32 min'],'fish','still / 4-frame line/water / loose plank'),
'boat':(['rowing: 30 min shop leg; 1 crate; no fuel','tug: 20 min shop leg; 2 crates; 4 legs per tank','speedboat: 10 min shop leg; 3 crates; 6 legs per tank'],'row','moored / 4-frame oars/wake / hull leak or propeller jam'),
'door':(['greet visitor / 8 min','greet / 7 min; proposed peek reveals 1 visitor identity','greet / 6 min; proposed visitor patience 30 vs 20 min'],'greet','closed / on n/a for door tiers / jammed latch'),
'single':(['one usable interaction; no mechanical reason for tiers'],'reach_use','idle / 4-frame use if applicable / loose fitting'),
}
SIZES={'door':[13,24],'fridge':[12,24],'cooker':[18,15],'broom':[8,23],'petbowl':[10,5],'tv':[28,23],'bookshelf':[20,28],'piano':[25,18],'bed':[30,14],'phone':[15,18],'desk':[25,20],'basin':[15,28],'toilet':[13,18],'telescope':[23,23],'lamp':[30,35],'garden':[30,18],'jetty':[55,15],'boat':[55,24],'shop':[33,30],'tank':[38,26],'fishfood':[8,12],'barometer':[18,22],'radio':[24,20],'console':[28,22],'gadgets':[28,20],'shower':[18,30],'lift':[22,34],'wateringcan':[8,12],'diveinner':[13,24],'diveouter':[13,24],'drums':[20,18],'accordion':[18,20],'gramophone':[16,20]}
spaces=[]
for line in DATA.strip().splitlines():
    v=[x.strip() for x in line.split('|')]; id,name,cat,deps,activities,unlock,layout,items,props,decision=v
    size=[110,35] if cat=='standard' else ([105,35] if cat in ['theme','underground'] and id=='lair' or cat=='theme' else [55,35])
    overrides={'lamp':[95,35],'ensuite':[36,35],'lift':[22,35],'stairs':[10,35],'slide':[14,35],'roof':[110,20],'pool_changing':[66,35],'gym_changing':[66,35],'pub_wc':[44,35],'service_wc':[44,35],'bowling':[165,35],'kitchen_bay':[55,35],'garden':[55,25],'greenhouse':[66,35],'orchard':[88,40],'jetty':[55,15],'boathouse':[110,50],'shop':[66,35],'lido':[110,45],'rescue':[110,40],'wind':[44,70],'funicular':[55,70],'geothermal':[110,50],'sea_tunnel':[165,35],'satellite':[66,50],'testing_yard':[110,35],'solar':[110,35],'solar_tracker':[66,35],'garage':[0,0]}
    size=overrides.get(id,size)
    if id=='lair':size=[110,35]
    placement={'lantern_cap':'always topmost inset cap; no middle slot','standard':'saved random middle slot','subroom':'inside parent; no independent slot','service_bay':'rear amenity bay attached to parent','service_core':'aligned service core; follows saved floor exits','extension':'parent-attached bay; integer structural seam','island':'island/shore terrace; no tower stack position','underground':'concealed below terrain; revealed only on unlock','destination':'off-island; boat route','theme':'inside imagination room; interchangeable set','retired':'no placement; superseded'}[cat]
    if id=='kitchen':placement='fixed base / entrance'
    if id=='bedroom':placement='immediately beneath lamp; moves with tower'
    if id=='lamp':placement='always topmost'
    its=[]
    for pair in items.split(','):
        if pair=='none':continue
        a,p=pair.split(':');its.append({'id':a,'profile':p,'dimensions':SIZES.get(a,[22,20])})
    if id=='aquarium':pass
    spaces.append(dict(space_id=id,name=name,category=cat,placement_rule=placement,stack_eligible=cat=='standard',dimensions=size,dependencies=deps,activities=activities,unlock_challenge=unlock,layout=layout,items=its,props=[] if props=='none' else props.split(','),decision=decision,source='docs/EXPANSION_DESIGN.md',priority='P0' if id in ['kitchen','living','bedroom','lamp'] else 'P1' if id in ['weather','lair','workshop','lift'] else 'P2'))
# Aquarium exists independently of the possible later marine lab.
spaces.insert(4,dict(space_id='aquarium',name='Aquarium',category='standard',placement_rule='saved random middle slot',stack_eligible=True,dimensions=[110,35],dependencies='Fishy Business mission; fish specimens',activities='Feed fish; balance habitat; study sea life',unlock_challenge='Current Fishy Business mission; proposed varied habitat match and tank-balance puzzle',layout='Tank left/centre; feed station right; clear floor lane',items=[{'id':'tank','profile':'capacity','dimensions':[38,26]},{'id':'fishfood','profile':'single','dimensions':[8,12]}],props=['habitat_chart','fish_variants','tank_plants'],decision='runtime hook; ecology mini-game proposal',source='docs/FOR_CODEX.md; docs/EXPANSION_DESIGN.md',priority='P1'))
for s in spaces:
    if s['space_id'] in ['kitchen','living','bedroom','lamp','ensuite']:s['source']='docs/PRODUCTION_ASSET_KIT.md; docs/CODEX_BRIEF.md'
    if s['space_id'] in ['stairs','roof','kitchen_bay','gaming_bay']:s['source']+='; HANDOFF_TO_CLAUDE.md'
# Owner-specific equipment names remain separate from shared runtime ids; item profiles supply proposed benefits.
(HERE/'spaces.json').write_text(json.dumps(spaces,indent=2)+'\n')
(HERE/'item-profiles.json').write_text(json.dumps({k:{'benefits':v[0],'keeper_pose':v[1],'visual_cues':v[2]} for k,v in PROFILES.items()},indent=2)+'\n')
print(len(spaces),'spaces authored')
